### ISSUE TITLE
Improve behaviour when clicking on real link

### ISSUE THREAD

**Issue by kismet010** [ptcong/js-popunder#10]
The script opens the popunder and refresh the current page when the user clicks on any part of the screen. This way it seems broken, because if the user clicks on an actual link, he will see the same page as nothing has changed.

Is there any solution for this?

**Comment by ptcong** [comment]
I think you're missing flash, or are you browing on mobile ?

**Comment by kismet010** [comment]
Chrome 43 on GNU/Linux, so no flash.
But the thing is that the script is not redirecting to the link the user has clicked, just refreshing the current page

**Comment by ptcong** [comment]
This script require flash, if your browser does not have flash, it will try to use javascript to make popunder, but it can't good as use flash.

**Comment by kismet010** [comment]
Then you must say in your site that flash is required for the script to work correctly
