### ISSUE TITLE
Chrome 41+ blocks most popunders and opens in foreground

### ISSUE THREAD

**Issue by ctash** [ptcong/js-popunder#3]
Chrome 41+ Mac: Popunder windows work, tabs do not.
Chrome 41+ Win: Neither popunder windows, nor tabs work.

Note: there is no warning from Chrome, they just launch in the foreground.

**Comment by ptcong** [comment]
Ok, i just update to version 2.2 to work with chrome 41.
But the blur feature now is lost.
I'm working on this.

**Comment by Regul777** [comment]
I tried Chrome 41+  Mac: popunder windows and tabs both opens for me in foreground, so they both doesn't work for me.

**Comment by ptcong** [comment]
Chrome 41 change somethings to prevent popunder open in background.
Yes, i'm working on this

**Comment by leonardoligas** [comment]
any news?

**Comment by dinnyosz** [comment]
Hi Ptcong, 

do you have any news about this issue? 
Thx for your work

**Comment by ptcong** [comment]
Oh, nothing news, i think google have killed the feature.

**Comment by ptcong** [comment]
I have released a new version that bring back the feature, works on firefox, chrome.
