### ISSUE TITLE
Pop up instead pop under

### ISSUE THREAD

**Issue by darekodz** [ptcong/js-popunder#6]
This solution doesn't work for me. It shows pop up instead of pop under. I've increased chromeDelay param but it didn't help. Here is example - actually this is a test page from you project:
http://ric.hekko.pl/temp/popunder9/trunk/test.html

Any idea why is that?

**Comment by ptcong** [comment]
See,
```js
SmartPopunder.make('http://example.com/newwindow', {newTab: false, chromeDelay: 50000});
```
You set `newTab: false`, then it will create a pop on new window (not on tab).
If you mean pop under is a pop that not focused after created, chrome killed the feature on version 41+. Can't blur the pop under now, in other worlds can't make focus to main window after created a pop up/under.

`chromeDelay` option is time between creating 2 pops

**Comment by darekodz** [comment]
Hi ptcong,
Thanks you very much for your quick answer.
To confirm - is it possible to show (somehow) the pop-under in chrome browser using this script? Can be new window, tab, whatever...

Thanks!

**Comment by ptcong** [comment]
Ok, to ensure that you are understanding like me, this script provider a way to make pop on window, new tab. First time, blur feature (focus current window after created a pop) can works on chrome, firefox, safari. But after Chrome release version 41, it killed the feature. So now it only can make pop on new window, new tab without blurring 
To make pop on new window
```
SmartPopunder.make('http://example.com/newwindow', { newTab: false });
```
To make pop on new tab
```
SmartPopunder.make('http://example.com/newwindow', { newTab: true });
```

**Comment by darekodz** [comment]
Ok - thank you very much for this clarification. 
For me it means that I have find/write my own script which can do pop under on chrome. I saw such pop unders on some pages, e.g. http://vidtv.pl/ or redtube.com . Do you know how they do this?

**Comment by ptcong** [comment]
They use flash to make pop under, it works on Chrome 41 but on Chrome 43, it will be killed

**Comment by ptcong** [comment]
Ok try new version 2.4.0, i have implemented flash to make popunder works on chrome, firefox
