### ISSUE TITLE
PopUnder for mobile / new chrome

### ISSUE THREAD

**Issue by Chomer** [ptcong/js-popunder#7]
On some websites there is used different approach to display popunder on the mobile devices and new chrome versions. Link is being opened in the new tab and current tab location is being replaced with ad url. This solution can be meet in the site like: http://kat.cr . Maybe it would be useful to add also this kind of option as well.

**Comment by ptcong** [comment]
Thank for your suggestions.
I have implemented the feature for Firefox 38+, Chrome 41+, IE 11.
Check the new version.

**Comment by ptcong** [comment]
@Chomer  i just updated v 2.4.4, its works on Mobile, new Chrome like kat.cr

**Comment by Chomer** [comment]
@ptcong Thank you. There would be needed some adjustment. When user clicks the link then new tab should be opened with href value in the location. When clicks somewhere else then it can be a current window.
