### ISSUE TITLE
Pop-under doesn't work for Chrome 43

### ISSUE THREAD

**Issue by yoris** [ptcong/js-popunder#8]
The popunder is being displayed as a pop-up even with the flash solution

**Comment by ptcong** [comment]
Yes, like i said previous days before, Chrome 43 will killed flash pop-under.
But it flash pop-under still works on Chrome 43 on Mac OS (i'm using).

And i just updated version 2.4.4 that make pop-up newTab + blur works on all browsers.

**Comment by Regul777** [comment]
I've just checked your version 2.4.4 at my Mac OS 10.10 with Chrome 43 and pop-under doesn't blur. Is it right to say, that you mean that pop-under at Mac OS works, but without blur?

**Comment by ptcong** [comment]
To ensure flash works, you must run with http:// protocol, don't use file:// protocol. 
This code works on Chrome 43 + Mac OS
```
SmartPopunder.make('http://example.com/newwindow', {newTab: false, blur: true});
```

**Comment by ptcong** [comment]
Ah shit, Chrome just update a patch, that fixed on Mac OS, now blur not work on Chrome 43, mac OS

**Comment by elzerox** [comment]
Shit... any solution?
